repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.4
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest-and-mypy
        name: Run tests and type checking
        entry: make all_test
        language: system
        pass_filenames: false
        stages: [push]