site_name: GIRAFFE Documentation
site_description: Documentation for GIRAFFE - Genetic Programming for Ensemble Model Fusion
repo_url: https://github.com/damiankucharski/GIRAFFE
theme:
  name: material
  palette:
    primary: indigo
    accent: orange
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

nav:
  - Home: index.md
  - API Reference:
    - Core: api/core.md
    - Nodes: api/nodes.md
    - Operators: api/operators.md
    - Evolution: api/evolution.md
    - Backend: api/backend.md
    - Utilities: api/utilities.md
  - Development: 
    - Contributing: development/contributing.md
